version: '3'
services:
  nginx:
    container_name: utd-nginx
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '80:80'
  mongo:
    container_name: utd-mongo
    restart: always
    image: 'mongo:latest'
    volumes:
      - /data/db:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
  api:
    container_name: utd-api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    depends_on:
      - mongo
  client:
    container_name: utd-client
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
