version: "3"
services:
  mongo:
    container_name: uptimedown_mongodb
    restart: ${RESTART}
    image: 'mongo:latest'
    command: [--auth]
    volumes:
      - ./data/db:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"
  nginx:
    container_name: uptimedown_nginx
    restart: ${RESTART}
    build: nginx
    depends_on:
      - client
      - api
    ports:
      - "${PORT_HTTP}:80"
    volumes:
      - ./logs:/var/log/nginx
      - ./production:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  client:
    container_name: uptimedown_client
    build:
      dockerfile: docker/client/Dockerfile
      context: ..
    volumes:
      - /app/node_modules
      - ./production:/app/production
  api:
    container_name: uptimedown_api
    restart: ${RESTART}
    build:
      dockerfile: docker/api/Dockerfile
      context: ..
    depends_on:
      - mongo
  worker:
    container_name: uptimedown_worker
    restart: ${RESTART}
    build:
      dockerfile: docker/worker/Dockerfile
      context: ..
    depends_on:
      - mongo

    
